# ---------- BUILD STAGE ----------
FROM node:14-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build


# ---------- NGINX STAGE ----------
FROM nginx:1.27-alpine

COPY --from=build /app/dist/client /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]